// flow-typed signature: 51b7e94f159092fb1d346d1c4167f42a
// flow-typed version: <<STUB>>/@types/graphql_v^0.13.4/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/graphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/graphql' {
  declare module.exports: any;
}
